"""Language dictionary for the Manim animation.

The slide code uses exact Portuguese text as dictionary keys. Missing
translations intentionally fall back to Portuguese so a partially translated
language can still render while new entries are added.
"""

LANGUAGES = {
    "pt": {},
    "en": {
        "Equil?brio entre gera??o e carga": "Balance Between Generation and Load",
        "Desequil?brio de pot?ncia": "Power Imbalance",
        "Energia cin?tica e in?rcia": "Kinetic Energy and Inertia",
        "Equa??o de oscila??o": "Swing Equation",
        "Frequ?ncia e constante de in?rcia": "Frequency and inertia constant",
        "Condi??o m?nima de in?rcia": "Minimum Inertia Condition",
        "Estabilidade angular": "Angular Stability",
        "In?rcia sint?tica e Grid-Forming": "Synthetic Inertia and Grid-Forming",
        "Nadir de frequ?ncia vs RoCoF": "Frequency Nadir vs RoCoF",
        "Resumo": "Summary",
        "frequ?ncia": "frequency",
        "tempo": "time",
        "Turbina": "Turbine",
        "Gerador": "Generator",
        "Rede": "Grid",
        "Carga": "Load",
        "regi?o cr?tica": "critical region",
        "regi?o segura": "safe region",
        "alta in?rcia": "high inertia",
        "baixa in?rcia": "low inertia",
        "Baixa in?rcia causa maior RoCoF.": "Low inertia causes higher RoCoF.",
        "Sistema est?vel": "Stable system",
        "in?rcia suficiente": "sufficient inertia",
        "amortecimento suficiente": "sufficient damping",
        "controle adequado": "adequate control",
        "maior RoCoF": "higher RoCoF",
        "menor tempo para atua??o dos controles": "less time for control action",
    },
    "de": {
        "Equil?brio entre gera??o e carga": "Gleichgewicht zwischen Erzeugung und Last",
        "Desequil?brio de pot?ncia": "Leistungsungleichgewicht",
        "Energia cin?tica e in?rcia": "Kinetische Energie und Tr?gheit",
        "Equa??o de oscila??o": "Schwingungsgleichung",
        "Frequ?ncia e constante de in?rcia": "Frequenz und Tr?gheitskonstante",
        "Condi??o m?nima de in?rcia": "Mindesttr?gheitsbedingung",
        "Estabilidade angular": "Winkelstabilit?t",
        "In?rcia sint?tica e Grid-Forming": "Synthetische Tr?gheit und Grid-Forming",
        "Nadir de frequ?ncia vs RoCoF": "Frequenznadir vs RoCoF",
        "Resumo": "Zusammenfassung",
        "frequ?ncia": "Frequenz",
        "tempo": "Zeit",
        "Turbina": "Turbine",
        "Gerador": "Generator",
        "Rede": "Netz",
        "Carga": "Last",
        "regi?o cr?tica": "kritischer Bereich",
        "regi?o segura": "sicherer Bereich",
        "alta in?rcia": "hohe Tr?gheit",
        "baixa in?rcia": "geringe Tr?gheit",
        "Baixa in?rcia causa maior RoCoF.": "Geringe Tr?gheit verursacht h?heren RoCoF.",
        "Sistema est?vel": "Stabiles System",
        "in?rcia suficiente": "ausreichende Tr?gheit",
        "amortecimento suficiente": "ausreichende D?mpfung",
        "controle adequado": "geeignete Regelung",
        "maior RoCoF": "h?herer RoCoF",
        "menor tempo para atua??o dos controles": "weniger Zeit f?r Regeleingriffe",
    },
    "zh": {
        "Equil?brio entre gera??o e carga": "???????",
        "Desequil?brio de pot?ncia": "?????",
        "Energia cin?tica e in?rcia": "?????",
        "Equa??o de oscila??o": "????",
        "Frequ?ncia e constante de in?rcia": "???????",
        "Condi??o m?nima de in?rcia": "??????",
        "Estabilidade angular": "????",
        "In?rcia sint?tica e Grid-Forming": "??????????",
        "Nadir de frequ?ncia vs RoCoF": "??????RoCoF",
        "Resumo": "??",
        "frequ?ncia": "??",
        "tempo": "??",
        "Turbina": "???",
        "Gerador": "???",
        "Rede": "??",
        "Carga": "??",
        "regi?o cr?tica": "????",
        "regi?o segura": "????",
        "alta in?rcia": "???",
        "baixa in?rcia": "???",
        "Baixa in?rcia causa maior RoCoF.": "?????????RoCoF?",
        "Sistema est?vel": "????",
        "in?rcia suficiente": "????",
        "amortecimento suficiente": "????",
        "controle adequado": "????",
        "maior RoCoF": "??RoCoF",
        "menor tempo para atua??o dos controles": "????????",
    },
}
